### ISSUE TITLE
Sudden loss of sqs queue

### ISSUE THREAD

**Issue by ruuts** [tawan/active-elastic-job#43]
Hi,

Recently we experience a suddenly loss of the SQS queue.
An exception like this is thrown:

```
ActiveJob::QueueAdapters::ActiveElasticJobAdapter::NonExistentQueue:
The job is bound to queue at <queue_name>.
Unfortunately a queue with this name does not exist in this region.
Either create an Amazon SQS queue named <queue_name> - you can do this in AWS console,
make sure to select region '<region>' - or you select another queue for your jobs.
```

We run multi threaded. Not all threads / processes seem to throw this error.
And it's seems to occur when there are relatively long running jobs 10 + seconds.

We run version 1.4.2.

Going to investigate further.

**Comment by tawan** [comment]
Hi @ruuts ,

Any news on the possible source of this error? This gem throws the mentioned Error only of the AWS Client throws the error. See  [here](https://git.io/vi0d7)

Cheers,

Tawan

**Comment by ruuts** [comment]
@tawan thx for reaching out.

Problems seem to went away after updating the aws-sdk. But i have seen it again one or two times after we deployed that.

I guess its not something related to active elastic job.

When i know more i will post it here.

**Comment by ruuts** [comment]
@tawan still experiencing this issue. Its to weird. We will investigate further. @rscheepmaker fyi

**Comment by eamon-hguk** [comment]
I still get this issue, and I have all the latest AWS gems, had to downgrade to the 1.7 version.

Unfortunately a queue with this name does not exist in this
            region. Either create an Amazon SQS queue named staging_mailer_queue -
            you can do this in AWS console, make sure to select region
            '' - or you
            select another queue for your jobs.

**Comment by cschulte22** [comment]
I just spent some time debugging a similar issue on my end.  `job.perform_now` was working fine, but any call to `job.perform_later` would trigger the `NonExistentQueue` error.

Turns out that if you're using the default ElasticBeanstalk IAM permissions, you'll get the `AWSElasticBeanstalkWorkerTier` policy, which doesn't give you enough access to SQS.

Specifically, this line of code was triggering the error for me: https://github.com/tawan/active-elastic-job/blob/8a870e6ca4542438d2ed167ed2cb9b1473ee702d/lib/active_job/queue_adapters/active_elastic_job_adapter.rb#L141

The lookup to get the queue url was failing because of limited default permissions, which then triggered the `NonExistentQueue` error.

The fix that worked for me was to create a new policy that Allowed all actions on that specific SQS arn, and then attaching it to the beanstalk worker role (and the web role if you have different ones or a web tier that needs to call `perform_later` on jobs).

On a different note, the error message is incorrect too when it gives you the empty region ("make sure to select region ''").  The problem is here: https://github.com/tawan/active-elastic-job/blob/8a870e6ca4542438d2ed167ed2cb9b1473ee702d/lib/active_job/queue_adapters/active_elastic_job_adapter.rb#L180

`config.aws_region` is `nil` unless you explicitly set it in the configuration section.  By default (if you're using role based permissions) it won't be set there.  Instead we should be grabbing it from the instantiated client:

`aws_sqs_client.config.region`

Let me know if you want me to submit a PR for it - figured it's probably not worth the trouble since it's just a quick one line change.

**Comment by fguillen** [comment]
I am having the same error: 

```
ActiveJob::QueueAdapters::ActiveElasticJobAdapter::NonExistentQueue:             The job is bound to queue at production-campaignplatform-activejobs.
            Unfortunately a queue with this name does not exist in this
            region. Either create an Amazon SQS queue named production-campaignplatform-activejobs -
            you can do this in AWS console, make sure to select region
            '' - or you
            select another queue for your jobs.

	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/active_elastic_job-2.0.1/lib/active_job/queue_adapters/active_elastic_job_adapter.rb:144:in `rescue in queue_url'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/active_elastic_job-2.0.1/lib/active_job/queue_adapters/active_elastic_job_adapter.rb:138:in `queue_url'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/active_elastic_job-2.0.1/lib/active_job/queue_adapters/active_elastic_job_adapter.rb:121:in `build_message'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/active_elastic_job-2.0.1/lib/active_job/queue_adapters/active_elastic_job_adapter.rb:95:in `enqueue_at'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/active_elastic_job-2.0.1/lib/active_job/queue_adapters/active_elastic_job_adapter.rb:89:in `enqueue'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/active_elastic_job-2.0.1/lib/active_job/queue_adapters/active_elastic_job_adapter.rb:80:in `enqueue'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/activejob-5.0.2/lib/active_job/enqueuing.rb:76:in `block in enqueue'
```

The error is confused and not really intuitive, would be nice if the error:

- is responding with targeted queue name in quotes: 'production-campaignplatform-activejobs' the actual message made me think the targeted name was: 'production-campaignplatform-activejobs -'
- the proper aws region is showed properly
- the list of sqs available names are shown so we can infer from there if there is any kind of permission problem
